import Head from "next/head";
import dynamic from "next/dynamic";

export default function Home() {
  const MyComponent = dynamic(() => import("../../Modules/QuestionPage"), {
    ssr: false,
  });
  return (
    <>
      <Head>
        <title>Practice xapi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyComponent />
    </>
  );
}
